# Generated by Django 4.2.6 on 2024-03-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referene', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('file', models.FileField(upload_to='uploads/')),
                ('salaire', models.PositiveIntegerField(default=100000)),
                ('status', models.CharField(choices=[('O', 'OPENED'), ('P', 'PENDING'), ('C', 'CLOSED')], default='O', max_length=1)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('closed_date', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
